SELECT *
FROM portfolioproject..CovidDeaths
ORDER BY 3,4

-
-SELECT *
--FROM portfolioproject..covidvaccinations
--ORDER BY 3,4
SELECT Location,date,total_cases,new_cases,total_deaths,population
FROM portfolioproject..CovidDeaths
order by 1,2


--looking at total cases vs total deaths
SELECT Location , date, total_cases, total_deaths, (total_deaths/total_cases)*100 as Deathpercentage
FROM portfolioproject..CovidDeaths
WHERE location like '%india%'
order by 1,2

--looking at total cases vs population
SELECT Location , date,population,total_cases,(total_cases/population)*100 as infectedpercentage
FROM portfolioproject..CovidDeaths
WHERE location like '%india%'
order by 2,1


--looking at countrie with highest infected rates compared to population
SELECT Location ,population,max(total_cases) as highinfectedvcases,max(total_cases/population)*100 as maxinfectedpercentage
FROM portfolioproject..CovidDeaths
--WHERE location like '%india%'
group by location,population
order by maxinfectedpercentage desc


--highest death count per population
SELECT Location,population,max(cast(total_deaths as int)) as highdeathcases,max( total_deaths/population)*100 as maxdeathcountpercentage
FROM portfolioproject..CovidDeaths
--WHERE location like '%india%
WHERE CONTINENT IS NOT NULL
group by location,population
order by  highdeathcases desc


--GROUP BY LOCATION
SELECT location,max(cast(total_deaths as int)) as highdeathcases
FROM portfolioproject..CovidDeaths
--WHERE location like '%india%
WHERE CONTINENT IS NULL
group by location
order by highdeathcases desc

--SHOWING CONTINENTS WITH HIGHEST DEATH COUNTS PER POPULATION
SELECT continent ,max(cast(total_deaths as int)) as highdeathcases
FROM portfolioproject..CovidDeaths
--WHERE location like '%india%
WHERE CONTINENT IS not  NULL
group by continent
order by highdeathcases desc

--GLOBAL NUMBERS

SELECT SUM(CAST(NEW_CASES AS FLOAT)) AS GLOBALCASES,SUM(CAST(NEW_DEATHS AS FLOAT)) AS GLOBALDEATHS,(SUM(CAST(NEW_DEATHS AS FLOAT))/NULLIF(SUM(CAST(NEW_CASES AS FLOAT)),0))*100 AS GLOBALDEATHPERCENT
FROM portfolioproject..CovidDeaths
WHERE CONTINENT IS NOT NULL
--GROUP BY DATE
--ORDER BY DATE


--LOOKING AT TOTAL POPULATION VS VACCINATION 
SELECT DISTINCT DEA.CONTINENT,DEA.LOCATION,DEA.DATE,DEA.POPULATION,VAC.NEW_VACCINATIONS,
SUM(CONVERT(INT,VAC.NEW_VACCINATIONS)) OVER(PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION,DEA.DATE) AS ROLLING_VACCINATIONS,(ROLLING_VACCINATIONS/POPULATION) * 100
FROM portfolioproject..CovidDeaths DEA
JOIN PORTFOLIOPROJECT..COVIDVACCINATIONS VAC
ON DEA.LOCATION = VAC.LOCATION
AND DEA.DATE = VAC.DATE
WHERE DEA.CONTINENT IS NOT NULL
ORDER BY 2,3

--USE CTE

WITH POPVSVAC (CONTINENT,LOCATION,DATE,POPULATION,NEW_VACCINATIONS,ROLLING_VACCINATIONS)
AS
(
SELECT DISTINCT DEA.CONTINENT,DEA.LOCATION,DEA.DATE,DEA.POPULATION,VAC.NEW_VACCINATIONS,
SUM(CONVERT(INT,VAC.NEW_VACCINATIONS)) OVER(PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION,DEA.DATE) AS ROLLING_VACCINATIONS
--(ROLLING_VACCINATIONS/POPULATION) * 100
FROM portfolioproject..CovidDeaths DEA
JOIN PORTFOLIOPROJECT..COVIDVACCINATIONS VAC
ON DEA.LOCATION = VAC.LOCATION
AND DEA.DATE = VAC.DATE
WHERE DEA.CONTINENT IS NOT NULL
--ORDER BY 2,3
)
SELECT *,(ROLLING_VACCINATIONS/POPULATION)*100
FROM POPVSVAC


--TEMPTABLE

CREATE TABLE #PERCENTPOPULATIONVACCIANATED
(CONTINENT NVARCHAR(255),LOCATION NVARCHAR(255),DATE DATETIME,POPULATION NUMERIC,NEW_VACCINATIONS NUMERIC,ROLLING_VACCINATIONS NUMERIC)
INSERT INTO #PERCENTPOPULATIONVACCINATED

SELECT DISTINCT DEA.CONTINENT,DEA.LOCATION,DEA.DATE,DEA.POPULATION,VAC.NEW_VACCINATIONS,
SUM(CONVERT(INT,VAC.NEW_VACCINATIONS)) OVER(PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION,DEA.DATE) AS ROLLING_VACCINATIONS
--(ROLLING_VACCINATIONS/POPULATION) * 100
FROM portfolioproject..CovidDeaths DEA
JOIN PORTFOLIOPROJECT..COVIDVACCINATIONS VAC
ON DEA.LOCATION = VAC.LOCATION
AND DEA.DATE = VAC.DATE
WHERE DEA.CONTINENT IS NOT NULL
--ORDER BY 2,3
SELECT *,(ROLLING_VACCINATIONS/POPULATION)*100
FROM #PERCENTPOPULATIONVACCIANATED

--CREATE VIEW TO STORE DATA FOR LATER VISUALIZATIONS
CREATE VIEW PERCENTAGEPOPULATIONVACCINATED AS
SELECT DISTINCT DEA.CONTINENT,DEA.LOCATION,DEA.DATE,DEA.POPULATION,VAC.NEW_VACCINATIONS,
SUM(CONVERT(INT,VAC.NEW_VACCINATIONS)) OVER(PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION,DEA.DATE) AS ROLLING_VACCINATIONS
--(ROLLING_VACCINATIONS/POPULATION) * 100
FROM portfolioproject..CovidDeaths DEA
JOIN PORTFOLIOPROJECT..COVIDVACCINATIONS VAC
ON DEA.LOCATION = VAC.LOCATION
AND DEA.DATE = VAC.DATE
WHERE DEA.CONTINENT IS NOT NULL
--ORDER BY 2,3
GO

SELECT *,
FROM PERCENTAGEPOPULATIONVACCINATED



